name: Update CI-specific config files

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: List files (debug)
      run: ls -la

    - name: Upload config as artifact
      uses: actions/upload-artifact@v7
      with:
        name: npm-lockfile
        path: |
            package.json
            package-lock.json
        include-hidden-files: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore(deps): update CI-specific config files"
        title: "chore(deps): update CI-specific config files"
        body: |
          This PR updates CI-specific config files generated by `npm install`.
        branch: update-ci-config
        base: ${{ github.event.repository.default_branch }}
        add-paths: |
          package.json
          package-lock.json
        delete-branch: true
